<?php
/**
 * FraudDetectionResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fraudapi
 *
 * Easily and directly scan and block fraudulent security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FraudDetectionResult Class Doc Comment
 *
 * @category Class
 * @description Result of performing fraud detection on a document
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FraudDetectionResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FraudDetectionResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'successful' => 'bool',
        'clean_result' => 'bool',
        'fraud_risk_level' => 'double',
        'contains_financial_liability' => 'bool',
        'contains_sensitive_information_collection' => 'bool',
        'contains_asset_transfer' => 'bool',
        'contains_purchase_agreement' => 'bool',
        'contains_employment_agreement' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'successful' => null,
        'clean_result' => null,
        'fraud_risk_level' => 'double',
        'contains_financial_liability' => null,
        'contains_sensitive_information_collection' => null,
        'contains_asset_transfer' => null,
        'contains_purchase_agreement' => null,
        'contains_employment_agreement' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'successful' => 'Successful',
        'clean_result' => 'CleanResult',
        'fraud_risk_level' => 'FraudRiskLevel',
        'contains_financial_liability' => 'ContainsFinancialLiability',
        'contains_sensitive_information_collection' => 'ContainsSensitiveInformationCollection',
        'contains_asset_transfer' => 'ContainsAssetTransfer',
        'contains_purchase_agreement' => 'ContainsPurchaseAgreement',
        'contains_employment_agreement' => 'ContainsEmploymentAgreement'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'successful' => 'setSuccessful',
        'clean_result' => 'setCleanResult',
        'fraud_risk_level' => 'setFraudRiskLevel',
        'contains_financial_liability' => 'setContainsFinancialLiability',
        'contains_sensitive_information_collection' => 'setContainsSensitiveInformationCollection',
        'contains_asset_transfer' => 'setContainsAssetTransfer',
        'contains_purchase_agreement' => 'setContainsPurchaseAgreement',
        'contains_employment_agreement' => 'setContainsEmploymentAgreement'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'successful' => 'getSuccessful',
        'clean_result' => 'getCleanResult',
        'fraud_risk_level' => 'getFraudRiskLevel',
        'contains_financial_liability' => 'getContainsFinancialLiability',
        'contains_sensitive_information_collection' => 'getContainsSensitiveInformationCollection',
        'contains_asset_transfer' => 'getContainsAssetTransfer',
        'contains_purchase_agreement' => 'getContainsPurchaseAgreement',
        'contains_employment_agreement' => 'getContainsEmploymentAgreement'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['successful'] = isset($data['successful']) ? $data['successful'] : null;
        $this->container['clean_result'] = isset($data['clean_result']) ? $data['clean_result'] : null;
        $this->container['fraud_risk_level'] = isset($data['fraud_risk_level']) ? $data['fraud_risk_level'] : null;
        $this->container['contains_financial_liability'] = isset($data['contains_financial_liability']) ? $data['contains_financial_liability'] : null;
        $this->container['contains_sensitive_information_collection'] = isset($data['contains_sensitive_information_collection']) ? $data['contains_sensitive_information_collection'] : null;
        $this->container['contains_asset_transfer'] = isset($data['contains_asset_transfer']) ? $data['contains_asset_transfer'] : null;
        $this->container['contains_purchase_agreement'] = isset($data['contains_purchase_agreement']) ? $data['contains_purchase_agreement'] : null;
        $this->container['contains_employment_agreement'] = isset($data['contains_employment_agreement']) ? $data['contains_employment_agreement'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets successful
     *
     * @return bool
     */
    public function getSuccessful()
    {
        return $this->container['successful'];
    }

    /**
     * Sets successful
     *
     * @param bool $successful True if successful, false otherwise
     *
     * @return $this
     */
    public function setSuccessful($successful)
    {
        $this->container['successful'] = $successful;

        return $this;
    }

    /**
     * Gets clean_result
     *
     * @return bool
     */
    public function getCleanResult()
    {
        return $this->container['clean_result'];
    }

    /**
     * Sets clean_result
     *
     * @param bool $clean_result True if the document is clean, false if fraud threats were found
     *
     * @return $this
     */
    public function setCleanResult($clean_result)
    {
        $this->container['clean_result'] = $clean_result;

        return $this;
    }

    /**
     * Gets fraud_risk_level
     *
     * @return double
     */
    public function getFraudRiskLevel()
    {
        return $this->container['fraud_risk_level'];
    }

    /**
     * Sets fraud_risk_level
     *
     * @param double $fraud_risk_level Overall fraud risk level between 0.0 and 1.0
     *
     * @return $this
     */
    public function setFraudRiskLevel($fraud_risk_level)
    {
        $this->container['fraud_risk_level'] = $fraud_risk_level;

        return $this;
    }

    /**
     * Gets contains_financial_liability
     *
     * @return bool
     */
    public function getContainsFinancialLiability()
    {
        return $this->container['contains_financial_liability'];
    }

    /**
     * Sets contains_financial_liability
     *
     * @param bool $contains_financial_liability True if the document contains financial liability
     *
     * @return $this
     */
    public function setContainsFinancialLiability($contains_financial_liability)
    {
        $this->container['contains_financial_liability'] = $contains_financial_liability;

        return $this;
    }

    /**
     * Gets contains_sensitive_information_collection
     *
     * @return bool
     */
    public function getContainsSensitiveInformationCollection()
    {
        return $this->container['contains_sensitive_information_collection'];
    }

    /**
     * Sets contains_sensitive_information_collection
     *
     * @param bool $contains_sensitive_information_collection True if the document contains sensitive data collection from the recipient
     *
     * @return $this
     */
    public function setContainsSensitiveInformationCollection($contains_sensitive_information_collection)
    {
        $this->container['contains_sensitive_information_collection'] = $contains_sensitive_information_collection;

        return $this;
    }

    /**
     * Gets contains_asset_transfer
     *
     * @return bool
     */
    public function getContainsAssetTransfer()
    {
        return $this->container['contains_asset_transfer'];
    }

    /**
     * Sets contains_asset_transfer
     *
     * @param bool $contains_asset_transfer True if the document contains an asset transfer
     *
     * @return $this
     */
    public function setContainsAssetTransfer($contains_asset_transfer)
    {
        $this->container['contains_asset_transfer'] = $contains_asset_transfer;

        return $this;
    }

    /**
     * Gets contains_purchase_agreement
     *
     * @return bool
     */
    public function getContainsPurchaseAgreement()
    {
        return $this->container['contains_purchase_agreement'];
    }

    /**
     * Sets contains_purchase_agreement
     *
     * @param bool $contains_purchase_agreement True if the document contains a purchase agreement
     *
     * @return $this
     */
    public function setContainsPurchaseAgreement($contains_purchase_agreement)
    {
        $this->container['contains_purchase_agreement'] = $contains_purchase_agreement;

        return $this;
    }

    /**
     * Gets contains_employment_agreement
     *
     * @return bool
     */
    public function getContainsEmploymentAgreement()
    {
        return $this->container['contains_employment_agreement'];
    }

    /**
     * Sets contains_employment_agreement
     *
     * @param bool $contains_employment_agreement True if the document contains an employment agreement
     *
     * @return $this
     */
    public function setContainsEmploymentAgreement($contains_employment_agreement)
    {
        $this->container['contains_employment_agreement'] = $contains_employment_agreement;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


