<?php
/**
 * FraudDetectionResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fraudapi
 *
 * Easily and directly scan and block fraudulent security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FraudDetectionResultTest Class Doc Comment
 *
 * @category    Class
 * @description Result of performing fraud detection on a document
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FraudDetectionResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FraudDetectionResult"
     */
    public function testFraudDetectionResult()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "clean_result"
     */
    public function testPropertyCleanResult()
    {
    }

    /**
     * Test attribute "fraud_risk_level"
     */
    public function testPropertyFraudRiskLevel()
    {
    }

    /**
     * Test attribute "contains_financial_liability"
     */
    public function testPropertyContainsFinancialLiability()
    {
    }

    /**
     * Test attribute "contains_sensitive_information_collection"
     */
    public function testPropertyContainsSensitiveInformationCollection()
    {
    }

    /**
     * Test attribute "contains_asset_transfer"
     */
    public function testPropertyContainsAssetTransfer()
    {
    }

    /**
     * Test attribute "contains_purchase_agreement"
     */
    public function testPropertyContainsPurchaseAgreement()
    {
    }

    /**
     * Test attribute "contains_employment_agreement"
     */
    public function testPropertyContainsEmploymentAgreement()
    {
    }
}
